from django.urls import path

from .views import (
    AgentClaimJobView,
    AgentJobControlView,
    AgentJobLogsView,
    AgentJobStatusView,
    AgentPingView,
    AgentSetupGuideView,
    JobDetailView,
    JobLogsStreamView,
    JobRefreshStatusView,
    JobStartView,
    JobStopView,
    JobsListView,
    ScriptDefinitionDetailView,
    ScriptDefinitionHardDeleteView,
    ScriptsListView,
    TargetServerDetailView,
    TargetServerHardDeleteView,
    TargetServerTestConnectionView,
    TargetServersListView,
    UserProfileView,
)

urlpatterns = [
    path("me/", UserProfileView.as_view(), name="user-profile"),
    path("setup/agent/", AgentSetupGuideView.as_view(), name="setup-agent"),
    path("targets/", TargetServersListView.as_view(), name="targets-list"),
    path("targets/<int:id>/", TargetServerDetailView.as_view(), name="targets-detail"),
    path(
        "targets/<int:id>/hard-delete/",
        TargetServerHardDeleteView.as_view(),
        name="targets-hard-delete",
    ),
    path(
        "targets/<int:id>/test-connection/",
        TargetServerTestConnectionView.as_view(),
        name="targets-test-connection",
    ),
    path("scripts/", ScriptsListView.as_view(), name="scripts-list"),
    path("scripts/<int:id>/", ScriptDefinitionDetailView.as_view(), name="scripts-detail"),
    path(
        "scripts/<int:id>/hard-delete/",
        ScriptDefinitionHardDeleteView.as_view(),
        name="scripts-hard-delete",
    ),
    path("jobs/", JobsListView.as_view(), name="jobs-list"),
    path("jobs/start/", JobStartView.as_view(), name="jobs-start"),
    path("jobs/<uuid:id>/", JobDetailView.as_view(), name="jobs-detail"),
    path("jobs/<uuid:id>/logs/stream/", JobLogsStreamView.as_view(), name="jobs-logs-stream"),
    path("jobs/<uuid:id>/refresh-status/", JobRefreshStatusView.as_view(), name="jobs-refresh-status"),
    path("jobs/<uuid:id>/stop/", JobStopView.as_view(), name="jobs-stop"),
    path("agent/ping/", AgentPingView.as_view(), name="agent-ping"),
    path("agent/jobs/claim/", AgentClaimJobView.as_view(), name="agent-jobs-claim"),
    path("agent/jobs/<uuid:id>/logs/", AgentJobLogsView.as_view(), name="agent-jobs-logs"),
    path("agent/jobs/<uuid:id>/status/", AgentJobStatusView.as_view(), name="agent-jobs-status"),
    path("agent/jobs/<uuid:id>/control/", AgentJobControlView.as_view(), name="agent-jobs-control"),
]
